export const degrees = [
  "Bachelor of Science (BS)",
  "Master of Science (MS)",
  "Doctor of Philosophy (PHD)",
  "Bachelor of Technology (BTech)",
  "High School Diploma",
];

export const majors = [
  "Computer Science",
  "Mechanical Engineering",
  "Psychology",
  "Biology",
  "Business Administration",
  "Economics",
  "English Literature",
  "History",
  "Chemistry",
  "Mathematics",
  "Political Science",
  "Sociology",
  "Physics",
  "Art and Design",
  "Environmental Science",
  "Nursing",
  "Marketing",
  "Accounting",
  "Civil Engineering",
  "Architecture",
  "Music",
  "Education",
  "Communications",
  "Graphic Design",
  "Philosophy",
];
